version: "3.8"
services:
  backend:
    build: ./
    ports:
      - "3000:3000"
    env_file:
      - ./.env.production
    depends_on:
      - db-prod
  db-prod:
    image: mysql
    platform: linux/x86_64
    env_file:
      - ./.env.production
    ports:
      - "3306:3306"
    volumes:
      - prod-mysql-data:/var/lib/mysql
volumes:
  prod-mysql-data:
