version: "3.8"
services:
  backend:
    build: ./apps/backend
    ports:
      - "3000:3000"
    env_file:
      - ./apps/backend/.env.development
    depends_on:
      - db
  db:
    image: mysql:5.7
    env_file:
      - ./apps/backend/.env.development
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
